# ***Importing Libraries***

In [ ]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
np.set_printoptions(suppress=True)

# ***Printing Version of Tensorflow***

In [ ]:
tf.__version__

'2.5.0'

# ***Importing Data and presenting it***

In [ ]:
data=pd.read_csv("Churn_Modelling.csv")

In [ ]:
data


RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

# ***Label Encoding of Gender Column***

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Gender']=le.fit_transform(data['Gender'])
data['Gender']

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64

# ***Selecting Important Features***

In [ ]:
x=data.iloc[:,3:-1]
y=data.iloc[:,-1]
x

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France       0  ...          1               1        101348.88
1             608     Spain       0  ...          0               1        112542.58
2             502    France       0  ...          1               0        113931.57
3             699    France       0  ...          0               0         93826.63
4             850     Spain       0  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France       1  ...          1               0         96270.64
9996          516    France       1  ...          1               1        101699.77
9997          709    France       0  ...          0               1         42085.58
9998          772   Germany       1  ...          1               0         92888.52
9999          792    France       0  ...          1               0         38190.78

[10000 rows x 10 columns]

# ***Performing One Hot Encoding to Geography Column***

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([('encoder',OneHotEncoder(),[1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)


[[     1.        0.        0.   ...      1.        1.   101348.88]
 [     0.        0.        1.   ...      0.        1.   112542.58]
 [     1.        0.        0.   ...      1.        0.   113931.57]
 ...
 [     1.        0.        0.   ...      0.        1.    42085.58]
 [     0.        1.        0.   ...      1.        0.    92888.52]
 [     1.        0.        0.   ...      1.        0.    38190.78]]


# ***Categorizing Data into Training and Test Data***

In [ ]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)

# ***Performing Standardization to Data***

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_x=sc.fit_transform(train_x)
test_x=sc.fit_transform(test_x)

# ***Building Artificial Neural Network***

In [ ]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))


# ***Compiling Artificial Neural Network***

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# ***Fitting Data to Artificial Neural Network***

In [ ]:
ann.fit(train_x,train_y,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5685 - accuracy: 0.7455
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4820 - accuracy: 0.7975
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4487 - accuracy: 0.8019
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4322 - accuracy: 0.8104
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8134
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4149 - accuracy: 0.8185
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4068 - accuracy: 0.8249
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3959 - accuracy: 0.8329
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3846 - accuracy: 0.8376
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3747 - accura

## ***Predicting Result***

In [ ]:
print(ann.predict(sc.transform(test_x))>0.5),test_y

[[ True]
 [ True]
 [ True]
 ...
 [False]
 [ True]
 [ True]]


(None, 9394    0
 898     1
 2398    0
 5906    0
 2343    0
        ..
 1037    0
 2899    0
 9549    0
 2740    0
 6690    0
 Name: Exited, Length: 2000, dtype: int64)

# ***Making Confusion Matrix***

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(test_y,(ann.predict(test_x)>0.5))
cm

array([[1535,   60],
       [ 215,  190]])